import './globals.css'
import dynamic from "next/dynamic"
import Head from "next/head";
import Footer from '@/components/Footer';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const Navbar = dynamic(
  () => import('../components/Navbar'),
  { ssr: false}
)

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
       <meta charset="UTF-8" />
      </Head>
      <body className='bg-[#1a1a2e] flex flex-col h-screen justify-between'> 
        <Navbar/>
        <div className='mb-auto'>
        {children}
        </div>

        <Footer/>
      </body>
    </html>
  )
}
